#!/usr/bin/env bash

set -ex

# check commands are installed
which gmxdump   
which guamps_get
which guamps_set

if [[ ! $? -eq 0 ]]; then
    echo "Cannot find guamps executables"
    exit 1;
fi

pushd tests >/dev/null 2>&1
for script in test_*.sh; do
    name=${script%%.sh}
    echo "- $name"
    ./$script
    break
done
