#!/usr/bin/env bash

which guamps_get >/dev/null 2>&1
if [[ ! $? -eq 0 ]]; then
    echo "Cannot find guamps executables"
    exit 1;
fi

pushd tests >/dev/null 2>&1
for script in test_*.sh; do
    name=${script%%.sh}
    echo "- $name"
    ./$script
done
